from pathlib import Path
from datetime import date
import hashlib, json, html
from docx import Document
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT

ROOT=Path(__file__).resolve().parents[1]
PART2=ROOT/'papers/2026_V1I1_PIONEER_JULY_AUGUST_PART2'
ISSUE_DIR=ROOT/'issues/2026-v2-i1-august-2026'; PACK=ROOT/'ISSN_APPLICATION_PACK_2026-09-10'
ISSUE_DIR.mkdir(parents=True,exist_ok=True); PACK.mkdir(parents=True,exist_ok=True)
TITLE='CHIATECH JOURNAL'; ISSUE='Volume 2, Issue 1 · August 2026'; PREFIX='10.68232'; BASE='https://journal.chiatechsolutions.com'
ids=sorted([p.name for p in PART2.iterdir() if p.is_dir() and p.name.startswith('e') and len(p.name)==4],key=lambda x:int(x[1:]))
records=[]
for eid in ids:
 m=json.loads((PART2/eid/'metadata/article_metadata.json').read_text(encoding='utf-8'))
 records.append({'article_id':eid,'title':m.get('title',''),'source_issue':m.get('issue',''),'status':m.get('status',''),'html_url':f'{BASE}/papers/2026_V1I1_PIONEER_JULY_AUGUST_PART2/{eid}/html/{eid}.html','pdf_url':f'{BASE}/papers/2026_V1I1_PIONEER_JULY_AUGUST_PART2/{eid}/pdf/CHIATECH_JOURNAL_2026_V1I1_{eid}_PIONEER_PART2.pdf'})
(ISSUE_DIR/'issue_manifest.json').write_text(json.dumps({'title':TITLE,'volume':'2','issue':'1','publication_month':'AUGUST 2026','status':'PUBLIC_FINISHED_PAPERS_PENDING_ISSN_ASSIGNMENT','doi_prefix':PREFIX,'issn_print':'PENDING_ASSIGNMENT','issn_online':'PENDING_ASSIGNMENT','issn_l':'PENDING_DESIGNATION_BY_ISSN_SYSTEM','paper_count':len(records),'papers':records},indent=2,ensure_ascii=False),encoding='utf-8')
rows=''.join(f'<li><strong>{html.escape(r["article_id"])}</strong> — {html.escape(r["title"])}<br><a href="{r["html_url"]}">HTML</a> · <a href="{r["pdf_url"]}">PDF</a></li>' for r in records)
(ISSUE_DIR/'index.html').write_text(f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{ISSUE} | {TITLE}</title><meta name="description" content="{TITLE} {ISSUE}, with {len(records)} finished papers and pending ISSN assignment."><link rel="canonical" href="{BASE}/issues/2026-v2-i1-august-2026/"><link rel="stylesheet" href="/assets/css/style.css"><link rel="stylesheet" href="/assets/css/launch.css"></head><body><header class="site-header"><div class="container masthead"><a class="brand" href="/"><span class="brand-copy"><strong>{TITLE}</strong><small>Science · Technology · Engineering · Mathematics · Education · Humanities · Entrepreneurship · Management</small></span></a></div></header><main id="main-content"><section class="page-hero"><div class="container"><p class="eyebrow">Issue publication record</p><h1>{ISSUE}</h1><p class="lead">{TITLE} · finished papers e026–e058.</p><p><strong>ISSN Print:</strong> Pending assignment · <strong>ISSN Online:</strong> Pending assignment · <strong>ISSN-L:</strong> Pending designation · <strong>Crossref DOI prefix:</strong> {PREFIX}</p><p><a class="btn btn-accent" href="/issues/2026-v2-i1-august-2026/CHIATECH_JOURNAL_V2I1_AUGUST_2026_PRINT_MAIDEN_ISSUE.pdf">Download matching print maiden issue PDF</a></p></div></section><section class="section"><div class="container"><h2>Finished papers</h2><p>Each paper remains linked to its controlled HTML and PDF asset. DOI registration and ISSN assignment remain pending operator completion.</p><ol>{rows}</ol></div></section></main><footer class="site-footer"><div class="container footer-bottom"><span>© 2026 CHIA TECH SOLUTIONS AND RESOURCES LIMITED.</span><a href="/about/indexing-archiving/">Indexing, DOI &amp; Archiving</a></div></footer></body></html>''',encoding='utf-8')
pack=f'''# ISSN and Crossref application pack — {TITLE}\n\nPrepared: {date.today().isoformat()}\n\n## Publication identity\n- Title proper: {TITLE}\n- Publisher: CHIA TECH SOLUTIONS AND RESOURCES LIMITED\n- Country: Nigeria\n- Website: {BASE}\n- Issue: {ISSUE}\n- Finished-paper count: {len(records)} (e026–e058)\n- Crossref DOI prefix: `{PREFIX}` (confirmed from the supplied Crossref member notice)\n- ISSN Print: **PENDING ASSIGNMENT**\n- ISSN Online: **PENDING ASSIGNMENT**\n- ISSN-L: **PENDING DESIGNATION BY THE ISSN SYSTEM**\n\n## Separate media requests\n1. **Online/electronic application:** provide `{BASE}/issues/2026-v2-i1-august-2026/`.\n2. **Print application:** provide `{BASE}/issues/2026-v2-i1-august-2026/CHIATECH_JOURNAL_V2I1_AUGUST_2026_PRINT_MAIDEN_ISSUE.pdf`.\n\nISSN-L is designated by the ISSN system after the related records are established; it is not invented by the publisher.\n\n## Corporate account\nCreate the corporate publisher account at [issn.nln.gov.ng](https://issn.nln.gov.ng/clientregistration/registration). The authentic CAC certificate of incorporation must be uploaded. No CAC number is invented in this pack.\n\n## Attachments\n- `CHIATECH_ISSN_REQUEST_LETTERHEAD.docx` and its PDF version.\n- Authentic CAC certificate of incorporation.\n- Matching print maiden issue PDF.\n- `issues/2026-v2-i1-august-2026/issue_manifest.json`.\n\nThis repository update records the Crossref prefix and exposes the finished-paper issue package. It does not claim ISSN assignment, ISSN-L designation, account creation, submission or approval.\n'''
(PACK/'ISSN_APPLICATION_DATA.md').write_text(pack,encoding='utf-8')
(PACK/'crossref_status.json').write_text(json.dumps({'member_name':'CHIA TECH SOLUTIONS AND RESOURCES LIMITED','doi_prefix':PREFIX,'evidence':'User-supplied Crossref member notice dated 2026-09-10','status':'PREFIX_CONFIRMED_MEMBER_ACCOUNT','issn_print':'PENDING_ASSIGNMENT','issn_online':'PENDING_ASSIGNMENT','issn_l':'PENDING_DESIGNATION'},indent=2),encoding='utf-8')
(PACK/'finished_papers_manifest.json').write_text(json.dumps(records,indent=2,ensure_ascii=False),encoding='utf-8')
doc=Document(); sec=doc.sections[0]; sec.top_margin=Inches(.65); sec.bottom_margin=Inches(.65)
p=doc.add_paragraph(); p.alignment=WD_ALIGN_PARAGRAPH.CENTER; r=p.add_run('CHIA TECH SOLUTIONS AND RESOURCES LIMITED\n'); r.bold=True; r.font.size=Pt(16); r2=p.add_run('CHIATECH JOURNAL · ISSN APPLICATION LETTER'); r2.bold=True; r2.font.size=Pt(12)
p=doc.add_paragraph(); p.alignment=WD_ALIGN_PARAGRAPH.CENTER; p.add_run('Opposite Mini Campus, University of Abuja, Phase 1, Gwagwalada, Nigeria\nRegistered office: No. 5 Joseph Sarwuan Tarka Road, opposite House of Mercy International, North Bank, Makurdi, Benue State, Nigeria\nEmail: chiatechlibrary@gmail.com · Website: https://journal.chiatechsolutions.com').font.size=Pt(9)
doc.add_paragraph('Date: ____________________'); doc.add_paragraph('To: The Director, Nigerian National Library / ISSN National Centre for Nigeria'); doc.add_paragraph('Subject: Separate applications for Online and Print ISSN — CHIATECH JOURNAL, Volume 2, Issue 1, August 2026'); doc.add_paragraph('Dear Sir/Madam,')
doc.add_paragraph('CHIA TECH SOLUTIONS AND RESOURCES LIMITED requests separate ISSN applications for the electronic and print media of CHIATECH JOURNAL. The prepared issue is Volume 2, Issue 1, August 2026, containing 33 finished papers (e026–e058). The online issue is available at https://journal.chiatechsolutions.com/issues/2026-v2-i1-august-2026/. A matching print maiden issue PDF is enclosed.')
t=doc.add_table(rows=1,cols=2); t.alignment=WD_TABLE_ALIGNMENT.CENTER; t.style='Table Grid'; t.rows[0].cells[0].text='Media request'; t.rows[0].cells[1].text='Evidence / identifier'
for a,b in [('Online/electronic ISSN','Issue URL; ISSN pending assignment'),('Print ISSN','Matching print maiden issue PDF; ISSN pending assignment'),('ISSN-L','To be designated by the ISSN system'),('Crossref DOI prefix','10.68232')]:
 c=t.add_row().cells; c[0].text=a; c[1].text=b
doc.add_paragraph('We will provide the authentic CAC certificate of incorporation, corporate publisher details and any further evidence requested by the ISSN Centre. We understand that the online and print applications are separate media requests and that no ISSN or ISSN-L should be displayed as assigned until officially issued.')
doc.add_paragraph('Yours faithfully,\n\n______________________________\nAuthorised representative\nFor: CHIA TECH SOLUTIONS AND RESOURCES LIMITED')
doc.save(PACK/'CHIATECH_ISSN_REQUEST_LETTERHEAD.docx')
print(f'Built issue page and application pack for {len(records)} papers')
